// Auto-generated dynamic loader mapping slugs to chunk modules
import { CalculationResult } from '@/types/calculator';

type CalcFunction = (inputs: Record<string, any>) => CalculationResult;

const MODULE_LOADERS: Record<string, () => Promise<{ default?: any; [key: string]: any }>> = {
  datumZeit: () => import('@/data/calculators/datumZeit'),
  mathematik: () => import('@/data/calculators/mathematik'),
  finanzen: () => import('@/data/calculators/finanzen'),
  kredit: () => import('@/data/calculators/kredit'),
  auto: () => import('@/data/calculators/auto'),
  wohnen: () => import('@/data/calculators/wohnen'),
  haushalt: () => import('@/data/calculators/haushalt'),
  arbeit: () => import('@/data/calculators/arbeit'),
  gesundheit: () => import('@/data/calculators/gesundheit'),
  familie: () => import('@/data/calculators/familie'),
  bauen: () => import('@/data/calculators/bauen'),
  geometrie: () => import('@/data/calculators/geometrie'),
  einheiten: () => import('@/data/calculators/einheiten'),
  kochen: () => import('@/data/calculators/kochen'),
  business: () => import('@/data/calculators/business'),
  statistik: () => import('@/data/calculators/statistik'),
  extraDatumMath: () => import('@/data/calculators/extra/datumMath'),
  extraFinanzenKredit: () => import('@/data/calculators/extra/finanzenKredit'),
  extraWohnenHaushalt: () => import('@/data/calculators/extra/wohnenHaushalt'),
  extraAutoArbeit: () => import('@/data/calculators/extra/autoArbeit'),
  extraGesundheitFamilie: () => import('@/data/calculators/extra/gesundheitFamilie'),
  extraBauenGeometrie: () => import('@/data/calculators/extra/bauenGeometrie'),
  extraEinheitenKochen: () => import('@/data/calculators/extra/einheitenKochen'),
  extraBusinessStatistik: () => import('@/data/calculators/extra/businessStatistik'),
  steuernGehalt: () => import('@/data/calculators/steuernGehalt'),
};

const SLUG_TO_MODULE: Record<string, string> = {
  "brutto-netto-rechner": "steuernGehalt",
  "netto-brutto-rechner": "steuernGehalt",
  "einkommensteuerrechner": "steuernGehalt",
  "grenzsteuersatz-rechner": "steuernGehalt",
  "solidaritaetszuschlag-rechner": "steuernGehalt",
  "kirchensteuer-rechner": "steuernGehalt",
  "sozialabgaben-rechner": "steuernGehalt",
  "arbeitgeberkosten-rechner": "steuernGehalt",
  "minijob-rechner": "steuernGehalt",
  "midijob-rechner": "steuernGehalt",
  "bonus-netto-rechner": "steuernGehalt",
  "abfindungsrechner": "steuernGehalt",
  "renten-brutto-netto-rechner": "steuernGehalt",
  "umsatzsteuerrechner": "steuernGehalt",
  "altersrechner": "datumZeit",
  "alter-in-tagen": "datumZeit",
  "lebenszeit-in-stunden": "datumZeit",
  "alter-in-wochen": "datumZeit",
  "alter-in-monaten": "datumZeit",
  "altersunterschied": "datumZeit",
  "geburtstagsrechner": "datumZeit",
  "tage-bis-geburtstag": "datumZeit",
  "datumsdifferenz": "datumZeit",
  "wochen-zwischen-daten": "datumZeit",
  "monate-zwischen-daten": "datumZeit",
  "kalendertage-rechner": "datumZeit",
  "arbeitszeitrechner": "datumZeit",
  "tage-zwischen-zwei-daten": "datumZeit",
  "arbeitstage-rechner": "datumZeit",
  "werktage-rechner": "datumZeit",
  "datum-plus-tage": "datumZeit",
  "datum-minus-tage": "datumZeit",
  "schaltjahr-rechner": "datumZeit",
  "wochenrechner": "datumZeit",
  "zeitdifferenz-rechner": "datumZeit",
  "stundenrechner": "datumZeit",
  "countdown-rechner": "datumZeit",
  "prozentrechner": "mathematik",
  "prozentuale-veraenderung": "mathematik",
  "grundwert-rechner": "mathematik",
  "dreisatzrechner": "mathematik",
  "verhaeltnis-rechner": "mathematik",
  "bruchrechner": "mathematik",
  "dreieckrechner": "mathematik",
  "durchschnittsrechner": "mathematik",
  "pythagoras-rechner": "mathematik",
  "ggt-rechner": "mathematik",
  "kgv-rechner": "mathematik",
  "quadratwurzel-rechner": "mathematik",
  "zinseszinsrechner": "finanzen",
  "etf-sparplan-rechner": "finanzen",
  "sparrechner": "finanzen",
  "sparzielrechner": "finanzen",
  "inflationsrechner": "finanzen",
  "renditerechner": "finanzen",
  "notgroschen-rechner": "finanzen",
  "kreditrechner": "kredit",
  "ratenkreditrechner": "kredit",
  "autokreditrechner": "kredit",
  "tilgungsrechner": "kredit",
  "sondertilgungsrechner": "kredit",
  "restschuld-rechner": "kredit",
  "spritkostenrechner": "auto",
  "kraftstoffverbrauch-rechner": "auto",
  "pendlerpauschale-rechner": "auto",
  "fahrtkostenrechner": "auto",
  "elektroauto-ladekosten-rechner": "auto",
  "fahrzeit-rechner": "auto",
  "co2-auto-rechner": "auto",
  "mietbelastungsquote-rechner": "wohnen",
  "kaufnebenkosten-rechner": "wohnen",
  "immobilienrendite-rechner": "wohnen",
  "quadratmeterpreis-rechner": "wohnen",
  "mietbudget-rechner": "wohnen",
  "stromkostenrechner": "haushalt",
  "standby-kosten-rechner": "haushalt",
  "gaskostenrechner": "haushalt",
  "led-ersparnis-rechner": "haushalt",
  "stundenlohnrechner": "arbeit",
  "teilzeit-gehaltsrechner": "arbeit",
  "gehaltserhoehung-rechner": "arbeit",
  "urlaubstage-rechner": "arbeit",
  "bmi-rechner": "gesundheit",
  "kalorienbedarf-rechner": "gesundheit",
  "wasserbedarf-rechner": "gesundheit",
  "laufpace-rechner": "gesundheit",
  "geburtstermin-rechner": "familie",
  "fruchtbare-tage-rechner": "familie",
  "farbmengen-rechner": "bauen",
  "bodenbelag-rechner": "bauen",
  "betonrechner": "bauen",
  "kreisrechner": "geometrie",
  "zylinderrechner": "geometrie",
  "rechteckrechner": "geometrie",
  "laengen-umrechner": "einheiten",
  "temperatur-umrechner": "einheiten",
  "portionsrechner": "kochen",
  "backform-umrechner": "kochen",
  "gramm-in-ml-rechner": "kochen",
  "marge-rechner": "business",
  "mwst-rechner": "business",
  "break-even-rechner": "business",
  "rabattrechner": "business",
  "skontorechner": "business",
  "notendurchschnitt-rechner": "statistik",
  "standardabweichung-rechner": "statistik",
  "ohmsches-gesetz-rechner": "statistik",
  "renteneintritt-rechner": "extraDatumMath",
  "dienstjubilaeum-rechner": "extraDatumMath",
  "prozentualer-unterschied-rechner": "extraDatumMath",
  "prozent-von-prozent-rechner": "extraDatumMath",
  "promillerechner": "extraDatumMath",
  "antiproportionaler-dreisatz-rechner": "extraDatumMath",
  "bruch-in-dezimal-rechner": "extraDatumMath",
  "dezimal-in-bruch-rechner": "extraDatumMath",
  "kubikwurzel-rechner": "extraDatumMath",
  "n-te-wurzel-rechner": "extraDatumMath",
  "zehnerpotenzen-rechner": "extraDatumMath",
  "modulo-rechner": "extraDatumMath",
  "quersumme-rechner": "extraDatumMath",
  "hexadezimal-rechner": "extraDatumMath",
  "teiler-vielfache-rechner": "extraDatumMath",
  "tagesgeld-rechner": "extraFinanzenKredit",
  "festgeld-rechner": "extraFinanzenKredit",
  "spardauer-rechner": "extraFinanzenKredit",
  "kaufkraftverlust-rechner": "extraFinanzenKredit",
  "realzins-rechner": "extraFinanzenKredit",
  "dividendenrendite-rechner": "extraFinanzenKredit",
  "ewige-rente-rechner": "extraFinanzenKredit",
  "finanzielle-freiheit-rechner": "extraFinanzenKredit",
  "freistellungsauftrag-rechner": "extraFinanzenKredit",
  "kapitalertragsteuer-rechner": "extraFinanzenKredit",
  "depotgebuehren-rechner": "extraFinanzenKredit",
  "sparrate-rechner": "extraFinanzenKredit",
  "liquiditaetsreserve-rechner": "extraFinanzenKredit",
  "verdopplungszeit-rechner": "extraFinanzenKredit",
  "thesaurierend-vs-ausschuettend-rechner": "extraFinanzenKredit",
  "rentenluecke-rechner": "extraFinanzenKredit",
  "gold-rendite-rechner": "extraFinanzenKredit",
  "baufinanzierung-rechner": "extraFinanzenKredit",
  "ballonfinanzierung-rechner": "extraFinanzenKredit",
  "umschuldung-rechner": "extraFinanzenKredit",
  "dispozins-rechner": "extraFinanzenKredit",
  "maximaler-kredit-rechner": "extraFinanzenKredit",
  "zinsbindung-rechner": "extraFinanzenKredit",
  "volltilger-darlehen-rechner": "extraFinanzenKredit",
  "modernisierungskredit-rechner": "extraFinanzenKredit",
  "kreditvergleich-rechner": "extraFinanzenKredit",
  "gesamtzinsbelastung-rechner": "extraFinanzenKredit",
  "vorfaelligkeitsentschaedigung-rechner": "extraFinanzenKredit",
  "schuldentilgungsdauer-rechner": "extraFinanzenKredit",
  "forward-darlehen-rechner": "extraFinanzenKredit",
  "kreditlaufzeit-rechner": "extraFinanzenKredit",
  "kredit-restschuld-stichtag-rechner": "extraFinanzenKredit",
  "kreditrechner-ohne-eigenkapital": "extraFinanzenKredit",
  "effektivzins-kredit-rechner": "extraFinanzenKredit",
  "privatkredit-rechner": "extraFinanzenKredit",
  "zwischenfinanzierung-rechner": "extraFinanzenKredit",
  "mietminderung-rechner": "extraWohnenHaushalt",
  "staffelmiete-rechner": "extraWohnenHaushalt",
  "indexmiete-rechner": "extraWohnenHaushalt",
  "wohnflaeche-din-rechner": "extraWohnenHaushalt",
  "grundsteuer-reform-rechner": "extraWohnenHaushalt",
  "spekulationssteuer-immobilien-rechner": "extraWohnenHaushalt",
  "maklerprovision-rechner": "extraWohnenHaushalt",
  "grunderwerbsteuer-rechner": "extraWohnenHaushalt",
  "notar-grundbuch-kosten-rechner": "extraWohnenHaushalt",
  "instandhaltungsruecklage-rechner": "extraWohnenHaushalt",
  "modernisierungsumlage-rechner": "extraWohnenHaushalt",
  "mietkaution-zinsen-rechner": "extraWohnenHaushalt",
  "hausgeld-rechner": "extraWohnenHaushalt",
  "abschreibung-immobilien-rechner": "extraWohnenHaushalt",
  "mietrendite-brutto-netto-rechner": "extraWohnenHaushalt",
  "vorfaelligkeitsentschaedigung-baufinanzierung-rechner": "extraWohnenHaushalt",
  "abstandszahlung-rechner": "extraWohnenHaushalt",
  "warmmiete-zu-kaltmiete-rechner": "extraWohnenHaushalt",
  "untermiete-rechner": "extraWohnenHaushalt",
  "erbbaurecht-erbbauzins-rechner": "extraWohnenHaushalt",
  "kaufpreis-faktor-rechner": "extraWohnenHaushalt",
  "stromkosten-geraete-rechner": "extraWohnenHaushalt",
  "gasverbrauch-kwh-m3-rechner": "extraWohnenHaushalt",
  "balkonkraftwerk-ertrag-rechner": "extraWohnenHaushalt",
  "photovoltaik-amortisation-rechner": "extraWohnenHaushalt",
  "waermepumpe-stromkosten-rechner": "extraWohnenHaushalt",
  "heizkostenvergleich-rechner": "extraWohnenHaushalt",
  "warmwasserkosten-rechner": "extraWohnenHaushalt",
  "kuehlschrank-stromkosten-rechner": "extraWohnenHaushalt",
  "waschmaschine-kosten-rechner": "extraWohnenHaushalt",
  "trockner-kosten-rechner": "extraWohnenHaushalt",
  "spuelmaschine-kosten-rechner": "extraWohnenHaushalt",
  "fernseher-stromkosten-rechner": "extraWohnenHaushalt",
  "led-sparrechner": "extraWohnenHaushalt",
  "wasserverbrauch-haushalt-rechner": "extraWohnenHaushalt",
  "oelheizung-verbrauch-rechner": "extraWohnenHaushalt",
  "pelletheizung-verbrauch-rechner": "extraWohnenHaushalt",
  "klimaanlage-stromkosten-rechner": "extraWohnenHaushalt",
  "e-auto-ladekosten-zuhause-rechner": "extraWohnenHaushalt",
  "co2-abgabe-vermieter-mieter-rechner": "extraWohnenHaushalt",
  "lebensmittelbudget-rechner": "extraWohnenHaushalt",
  "energieeffizienzklasse-rechner": "extraWohnenHaushalt",
  "kfz-steuer-rechner": "extraAutoArbeit",
  "dienstwagen-1-prozent-rechner": "extraAutoArbeit",
  "fahrtenbuch-vs-1-prozent-rechner": "extraAutoArbeit",
  "leasingfaktor-rechner": "extraAutoArbeit",
  "auto-gesamtkosten-rechner": "extraAutoArbeit",
  "auto-wertverlust-rechner": "extraAutoArbeit",
  "bremsweg-rechner": "extraAutoArbeit",
  "bussgeld-rechner-geschwindigkeit": "extraAutoArbeit",
  "promillerechner-widmark": "extraAutoArbeit",
  "anhaenger-stuetzlast-rechner": "extraAutoArbeit",
  "reifen-abrollumfang-rechner": "extraAutoArbeit",
  "thg-quote-rechner": "extraAutoArbeit",
  "dienstfahrrad-jobrad-rechner": "extraAutoArbeit",
  "hybrid-auto-kosten-rechner": "extraAutoArbeit",
  "fahrgemeinschaft-sprit-rechner": "extraAutoArbeit",
  "autobahn-maut-rechner-vignette": "extraAutoArbeit",
  "motorrad-unterhaltskosten-rechner": "extraAutoArbeit",
  "lkw-maut-deutschland-rechner": "extraAutoArbeit",
  "kurzarbeitergeld-rechner": "extraAutoArbeit",
  "abfindung-fuenftelregelung-rechner": "extraAutoArbeit",
  "minijob-midijob-rechner": "extraAutoArbeit",
  "arbeitgeberanteil-sozialversicherung-rechner": "extraAutoArbeit",
  "kuendigungsfrist-arbeitnehmer-rechner": "extraAutoArbeit",
  "ueberstunden-auszahlung-rechner": "extraAutoArbeit",
  "firmenwagen-geldwerter-vorteil-rechner": "extraAutoArbeit",
  "krankengeld-rechner": "extraAutoArbeit",
  "mutterschaftsgeld-rechner": "extraAutoArbeit",
  "elternzeit-teilzeit-rechner": "extraAutoArbeit",
  "sabbatical-rechner": "extraAutoArbeit",
  "nachtzuschlag-sonntagszuschlag-rechner": "extraAutoArbeit",
  "vermoegenswirksame-leistungen-rechner": "extraAutoArbeit",
  "betriebliche-altersvorsorge-rechner": "extraAutoArbeit",
  "jahresgehalt-in-monatsgehalt-rechner": "extraAutoArbeit",
  "brutto-stundensatz-freiberufler-rechner": "extraAutoArbeit",
  "urlaubsabgeltung-rechner": "extraAutoArbeit",
  "arbeitslosengeld-1-rechner": "extraAutoArbeit",
  "buergergeld-anspruch-rechner": "extraAutoArbeit",
  "dienstjubilaeum-steuerfrei-rechner": "extraAutoArbeit",
  "dienstaufwandsentschaedigung-rechner": "extraAutoArbeit",
  "grundumsatz-bmr-rechner": "extraGesundheitFamilie",
  "leistungsumsatz-pal-rechner": "extraGesundheitFamilie",
  "makronaehrstoff-verteilung-rechner": "extraGesundheitFamilie",
  "idealgewicht-creff-rechner": "extraGesundheitFamilie",
  "koerperfettanteil-navy-rechner": "extraGesundheitFamilie",
  "waist-to-hip-ratio-rechner": "extraGesundheitFamilie",
  "waist-to-height-ratio-rechner": "extraGesundheitFamilie",
  "maximalpuls-hfmax-rechner": "extraGesundheitFamilie",
  "vo2max-cooper-test-rechner": "extraGesundheitFamilie",
  "one-rep-max-rechner": "extraGesundheitFamilie",
  "schritt-distanz-kalorien-rechner": "extraGesundheitFamilie",
  "schlafbedarfs-rechner": "extraGesundheitFamilie",
  "nikotin-rauchstopp-ersparnis-rechner": "extraGesundheitFamilie",
  "koffein-halbwertszeit-rechner": "extraGesundheitFamilie",
  "alkohol-abbau-rechner": "extraGesundheitFamilie",
  "intervallfasten-16-8-rechner": "extraGesundheitFamilie",
  "proteinbedarf-sportler-rechner": "extraGesundheitFamilie",
  "blutdruck-klassifikation-rechner": "extraGesundheitFamilie",
  "puls-trainingszonen-rechner": "extraGesundheitFamilie",
  "schwimmen-kalorienverbrauch-rechner": "extraGesundheitFamilie",
  "radfahren-kalorien-watt-rechner": "extraGesundheitFamilie",
  "elterngeld-basis-plus-rechner": "extraGesundheitFamilie",
  "kindergeld-rechner-2026": "extraGesundheitFamilie",
  "kinderzuschlag-kiz-rechner": "extraGesundheitFamilie",
  "unterhaltsvorschuss-rechner": "extraGesundheitFamilie",
  "duesseldorfer-tabelle-rechner": "extraGesundheitFamilie",
  "ehegattenunterhalt-trennungsunterhalt-rechner": "extraGesundheitFamilie",
  "schwangerschaftswoche-ssw-rechner": "extraGesundheitFamilie",
  "mutterschutzfristen-rechner": "extraGesundheitFamilie",
  "zykluslaenge-eisprung-rechner": "extraGesundheitFamilie",
  "chinesischer-empfaengniskalender-rechner": "extraGesundheitFamilie",
  "kindes-endgroesse-rechner": "extraGesundheitFamilie",
  "kindersitz-groesse-i-size-rechner": "extraGesundheitFamilie",
  "windelbudget-rechner": "extraGesundheitFamilie",
  "erstausstattung-baby-rechner": "extraGesundheitFamilie",
  "kita-gebuehren-rechner": "extraGesundheitFamilie",
  "betreuungsgeld-familiengeld-rechner": "extraGesundheitFamilie",
  "taschengeld-empfehlung-rechner": "extraGesundheitFamilie",
  "schulbedarfspaket-bu-t-rechner": "extraGesundheitFamilie",
  "kinderkrankentage-kinderkrankengeld-rechner": "extraGesundheitFamilie",
  "grosselternzeit-rechner": "extraGesundheitFamilie",
  "unterhalt-volljaehrige-kinder-rechner": "extraGesundheitFamilie",
  "ausbildungsunterhalt-bedarfskontrollbetrag-rechner": "extraGesundheitFamilie",
  "kinderbetreuungskosten-absetzen-rechner": "extraGesundheitFamilie",
  "estrich-rechner": "extraBauenGeometrie",
  "daemmung-u-wert-rechner": "extraBauenGeometrie",
  "dachflaeche-rechner": "extraBauenGeometrie",
  "bausteine-mauerwerk-rechner": "extraBauenGeometrie",
  "fliesenkleber-rechner": "extraBauenGeometrie",
  "aushub-erdarbeiten-rechner": "extraBauenGeometrie",
  "pflastersteine-rechner": "extraBauenGeometrie",
  "trockenbau-gipskarton-rechner": "extraBauenGeometrie",
  "fundament-rechner": "extraBauenGeometrie",
  "schalungssteine-rechner": "extraBauenGeometrie",
  "fassadenfarbe-rechner": "extraBauenGeometrie",
  "parkett-laminat-rechner": "extraBauenGeometrie",
  "tapetenrollen-rechner": "extraBauenGeometrie",
  "brennholz-raummeter-rechner": "extraBauenGeometrie",
  "putz-rechner": "extraBauenGeometrie",
  "zaun-pfosten-rechner": "extraBauenGeometrie",
  "regenwasser-zisterne-rechner": "extraBauenGeometrie",
  "treppen-stufen-rechner": "extraBauenGeometrie",
  "kies-splitt-rechner": "extraBauenGeometrie",
  "drainage-gefaelle-rechner": "extraBauenGeometrie",
  "baugrund-tragfaehigkeit-rechner": "extraBauenGeometrie",
  "holz-balken-durchbiegung-rechner": "extraBauenGeometrie",
  "beton-mischungsverhaeltnis-rechner": "extraBauenGeometrie",
  "dreieck-flaeche-rechner": "extraBauenGeometrie",
  "kreis-umfang-rechner": "extraBauenGeometrie",
  "kegel-volumen-rechner": "extraBauenGeometrie",
  "hohlzylinder-rohr-rechner": "extraBauenGeometrie",
  "pyramide-volumen-rechner": "extraBauenGeometrie",
  "trapez-flaeche-rechner": "extraBauenGeometrie",
  "parallelogramm-rechner": "extraBauenGeometrie",
  "rhombus-raute-rechner": "extraBauenGeometrie",
  "kugel-oberflaeche-rechner": "extraBauenGeometrie",
  "quader-volumen-rechner": "extraBauenGeometrie",
  "prisma-volumen-rechner": "extraBauenGeometrie",
  "sechseck-polygon-rechner": "extraBauenGeometrie",
  "ellipse-flaeche-rechner": "extraBauenGeometrie",
  "kreissegment-rechner": "extraBauenGeometrie",
  "bogenmass-grad-rechner": "extraBauenGeometrie",
  "satz-des-pythagoras-rechner": "extraBauenGeometrie",
  "sinussatz-kosinussatz-rechner": "extraBauenGeometrie",
  "vektor-skalarprodukt-rechner": "extraBauenGeometrie",
  "torus-volumen-rechner": "extraBauenGeometrie",
  "stumpf-kegel-rechner": "extraBauenGeometrie",
  "dreiecks-hoehen-rechner": "extraBauenGeometrie",
  "goldener-schnitt-rechner": "extraBauenGeometrie",
  "gewicht-masse-umrechner": "extraEinheitenKochen",
  "druck-umrechner": "extraEinheitenKochen",
  "geschwindigkeit-umrechner": "extraEinheitenKochen",
  "volumen-umrechner": "extraEinheitenKochen",
  "flaeche-umrechner": "extraEinheitenKochen",
  "energie-arbeit-umrechner": "extraEinheitenKochen",
  "leistung-umrechner": "extraEinheitenKochen",
  "daten-speicher-umrechner": "extraEinheitenKochen",
  "datenrate-bandbreite-umrechner": "extraEinheitenKochen",
  "drehmoment-umrechner": "extraEinheitenKochen",
  "kraft-umrechner": "extraEinheitenKochen",
  "kraftstoffverbrauch-umrechner": "extraEinheitenKochen",
  "roemische-zahlen-umrechner": "extraEinheitenKochen",
  "binaer-hex-dezimal-umrechner": "extraEinheitenKochen",
  "zoll-in-cm-rechner": "extraEinheitenKochen",
  "zeit-umrechner": "extraEinheitenKochen",
  "dichte-umrechner": "extraEinheitenKochen",
  "drehzahl-umfangsgeschwindigkeit-rechner": "extraEinheitenKochen",
  "beleuchtungsstaerke-lux-lumen-rechner": "extraEinheitenKochen",
  "elektrische-ladung-kapazitaet-rechner": "extraEinheitenKochen",
  "radioaktivitaet-strahlendosis-rechner": "extraEinheitenKochen",
  "viskositaet-umrechner": "extraEinheitenKochen",
  "schuhe-kleidergroessen-umrechner": "extraEinheitenKochen",
  "papierformat-din-rechner": "extraEinheitenKochen",
  "ringgroesse-umrechner": "extraEinheitenKochen",
  "dezibel-schalldruck-umrechner": "extraEinheitenKochen",
  "hefe-umrechner": "extraEinheitenKochen",
  "essloeffel-teeloeffel-gramm-rechner": "extraEinheitenKochen",
  "cups-in-gramm-rechner": "extraEinheitenKochen",
  "zucker-ersatz-rechner": "extraEinheitenKochen",
  "backzeit-temperatur-umluft-oberhitze-rechner": "extraEinheitenKochen",
  "fleisch-kerntemperatur-garzeit-rechner": "extraEinheitenKochen",
  "pizza-teig-rechner": "extraEinheitenKochen",
  "brot-backen-baeckermass-rechner": "extraEinheitenKochen",
  "alkohol-verkochungs-rechner": "extraEinheitenKochen",
  "eiweiss-eigelb-ersatz-rechner": "extraEinheitenKochen",
  "wasser-reis-verhaeltnis-rechner": "extraEinheitenKochen",
  "nudeln-rohmaerk-gewicht-rechner": "extraEinheitenKochen",
  "sauerteig-anstellgut-rechner": "extraEinheitenKochen",
  "marmelade-geliermittel-rechner": "extraEinheitenKochen",
  "kaffee-wasser-verhaeltnis-rechner": "extraEinheitenKochen",
  "cocktail-alkoholgehalt-rechner": "extraEinheitenKochen",
  "salz-lake-poekel-rechner": "extraEinheitenKochen",
  "frittieroel-temperatur-rauchpunkt-rechner": "extraEinheitenKochen",
  "fondue-raclette-mengen-rechner": "extraEinheitenKochen",
  "kuehlschrank-haltbarkeit-rechner": "extraEinheitenKochen",
  "tee-ziehzeit-temperatur-rechner": "extraEinheitenKochen",
  "kalorien-rezept-rechner": "extraEinheitenKochen",
  "schokolade-temperieren-rechner": "extraEinheitenKochen",
  "deckungsbeitrag-rechner": "extraBusinessStatistik",
  "roas-rechner": "extraBusinessStatistik",
  "roi-rechner": "extraBusinessStatistik",
  "ebit-ebitda-rechner": "extraBusinessStatistik",
  "cashflow-rechner": "extraBusinessStatistik",
  "liquiditaetsgrad-rechner": "extraBusinessStatistik",
  "working-capital-rechner": "extraBusinessStatistik",
  "umsatzrentabilitaet-rechner": "extraBusinessStatistik",
  "eigenkapitalrentabilitaet-rechner": "extraBusinessStatistik",
  "gesamtkapitalrentabilitaet-rechner": "extraBusinessStatistik",
  "kundengewinnungskosten-cac-rechner": "extraBusinessStatistik",
  "customer-lifetime-value-clv-rechner": "extraBusinessStatistik",
  "churn-rate-rechner": "extraBusinessStatistik",
  "lead-conversion-rate-rechner": "extraBusinessStatistik",
  "abschreibung-linear-degressiv-rechner": "extraBusinessStatistik",
  "skonto-jahreszins-rechner": "extraBusinessStatistik",
  "wareneinsatzquote-rechner": "extraBusinessStatistik",
  "lagerumschlagshaeufigkeit-rechner": "extraBusinessStatistik",
  "stundensatz-kalkulation-freiberufler-rechner": "extraBusinessStatistik",
  "mittelwert-median-modus-rechner": "extraBusinessStatistik",
  "varianz-standardabweichung-stichprobe-rechner": "extraBusinessStatistik",
  "korrelationskoeffizient-rechner": "extraBusinessStatistik",
  "z-score-normalverteilung-rechner": "extraBusinessStatistik",
  "p-wert-hypothesentest-rechner": "extraBusinessStatistik",
  "t-test-rechner": "extraBusinessStatistik",
  "konfidenzintervall-rechner": "extraBusinessStatistik",
  "stichprobengroesse-rechner": "extraBusinessStatistik",
  "quartile-box-plot-rechner": "extraBusinessStatistik",
  "binomialverteilung-rechner": "extraBusinessStatistik",
  "poisson-verteilung-rechner": "extraBusinessStatistik",
  "kombinatorik-n-ueber-k-rechner": "extraBusinessStatistik",
  "lineare-regression-rechner": "extraBusinessStatistik",
  "kovarianz-rechner": "extraBusinessStatistik",
  "variationskoeffizient-rechner": "extraBusinessStatistik",
  "geometrisches-mittel-rechner": "extraBusinessStatistik",
  "harmonisches-mittel-rechner": "extraBusinessStatistik",
  "bayes-theorem-rechner": "extraBusinessStatistik",
  "wahrscheinlichkeit-wuerfel-muenze-rechner": "extraBusinessStatistik",
  "perzentil-rechner": "extraBusinessStatistik",
  "effektstaerke-cohens-d-rechner": "extraBusinessStatistik",
  "chi-quadrat-unabhaengigkeitstest-rechner": "extraBusinessStatistik"
};

// In-Memory-Cache für bereits geladene Engines
const ENGINE_CACHE = new Map<string, CalcFunction>();

export async function loadCalculatorEngine(slug: string): Promise<CalcFunction | null> {
  if (ENGINE_CACHE.has(slug)) {
    return ENGINE_CACHE.get(slug)!;
  }

  const moduleKey = SLUG_TO_MODULE[slug];
  if (!moduleKey || !MODULE_LOADERS[moduleKey]) {
    return null;
  }

  try {
    const mod = await MODULE_LOADERS[moduleKey]();
    // Suche in den Arrays des Moduls
    for (const key of Object.keys(mod)) {
      const val = mod[key];
      if (Array.isArray(val)) {
        const found = val.find((c: any) => c.slug === slug || c.id === slug);
        if (found && typeof found.calculate === 'function') {
          ENGINE_CACHE.set(slug, found.calculate);
          return found.calculate;
        }
      }
    }
  } catch (err) {
    console.error('Failed to load calculator engine for slug:', slug, err);
  }

  return null;
}
